version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root